import {emitResidentStop} from './resident-stop.mjs';
const U='ptr<u32>',F='ptr<f32>',Q='ptr<u64>';
const p=(name,type='u32')=>({name,type});

// Closed selected execution realization: cold root establishment, one repeated
// device-owned scalar control/body32/completion sequence, and independent ports.
export function generateResidentEntries(name,L,external,runtime,maxRounds){
  const u=n=>`gpu.u32(${n})`,q=n=>`gpu.u64(${n}n)`,g=name+'_graph',pr=name+'_progress',o=name+'_output',s=name+'_session';
  const ex=external.length?', '+external.map(x=>x.name).join(', '):'',extra=external.map(({name,type})=>({name,type}));
  const main=[p('m',U),p('s',U),p('a',U),p('p',U),p('f',F),p('su',U),p('sf',F),p('vu',U),p('vf',F),p('sessionCounters',Q),p('authority',U),p('snapshot',U),p('encoded',U),p('command',U),p('admissionState0',U),p('admissionState1',U),p('out',U),...extra];
  const progressArgs='m,s,a,p,f,su,sf,vu,vf,sessionCounters'+ex;
  const sessionArgs='m,s,a,p,f,su,sf,authority,snapshot,encoded,command,admissionState0,admissionState1'+ex;
  const source={session:[],progress:[],output:[]},functions={session:[],progress:[],output:[]};
  function add(owner,role,parameters,body,block=1,continuation=false){const fn={name:name+'_'+role,kind:'kernel',parameters,returns:'void',launchConstraint:{grid:['1','1','1'],block:[String(block),'1','1']},...(continuation?{executionProfile:'device-continuation-v1'}:{})};functions[owner].push(fn);source[owner].push(`function ${fn.name}(${parameters.map(p=>p.name).join(',')}){\n${body}\n}\n`);return fn.name;}
  const bootstrap=add('session','bootstrap',[...main,p('initialRootInput',U),p('bootstrapResult',U),p('arena')],`bootstrapResult[${u(0)}]=${u(1)};if(${g}_initialize(m,arena)!==${u(0)}){return;}let replay=${s}_replay(initialRootInput,admissionState0,admissionState1,su${ex});if(replay!==${u(0)}){bootstrapResult[${u(0)}]=replay;return;}let root=${u(4294967295)};if(su[${u(L.scratchU32Words+8)}]===${u(0)}){root=${g}_admit(m,s,a,p,f,su,sf,admissionState0,${u(0)}${ex});}else{root=${g}_admit(m,s,a,p,f,su,sf,admissionState1,${u(0)}${ex});}if(root===${u(4294967295)}){bootstrapResult[${u(0)}]=${u(2)};return;}let generation=m[${u(L.nodeMeta)}+root*${u(16)}+${u(1)}];m[${u(2)}]=root;m[${u(3)}]=generation;m[${u(4)}]=${u(1)};gpu.atomic.storeReleaseDevice(authority,${u(0)},arena);gpu.atomic.storeReleaseDevice(authority,${u(1)},root);gpu.atomic.storeReleaseDevice(authority,${u(2)},generation);gpu.atomic.storeReleaseDevice(authority,${u(3)},${u(1)});let published=${o}_publish(m,a,p,f,authority,snapshot,encoded${ex});if(published!==${u(0)}){${emitResidentStop(11)}bootstrapResult[${u(0)}]=${u(3)};return;}bootstrapResult[${u(1)}]=root;bootstrapResult[${u(2)}]=generation;bootstrapResult[${u(3)}]=${u(1)};bootstrapResult[${u(0)}]=${u(0)};`);
  const runtimeByName=new Map(runtime.device.functions.map(f=>[f.name,f]));
  const call=(fn,special={})=>`${fn}(${runtimeByName.get(fn).parameters.map(p=>special[p.name]??p.name).join(',')})`;
  const cancel=call('mcgsTensorEvaluatorCancel',{slot:u(0),expectedSlotGeneration:`sessionCounters[${q(2)}]`,expectedRequestGeneration:`sessionCounters[${q(3)}]`});
  const latch=`if(m[${u(82)}]===${u(0)}){if(m[${u(17)}]!==${u(0)}){m[${u(82)}]=m[${u(17)}];}else if(gpu.atomic.loadAcquireDevice(authority,${u(16)})!==${u(0)}){m[${u(82)}]=${u(2)};}}`;
  const control=add('session','control',main,`${s}_apply(${sessionArgs});${latch}if(gpu.atomic.loadAcquireDevice(authority,${u(16)})!==${u(0)}&&m[${u(20)}]!==${u(0)}){${cancel};}`);
  const body=add('progress','body',main,`${pr}_body(m,sessionCounters${ex});`,32);
  const controller=add('progress','controller',main,`${latch}if(m[${u(82)}]!==${u(0)}){m[${u(84)}]=${u(1)};}${pr}_consume(${progressArgs});let cancelled=gpu.atomic.loadAcquireDevice(authority,${u(16)})!==${u(0)};if(!cancelled&&m[${u(17)}]===${u(0)}){${pr}_advance(${progressArgs});}if(m[${u(45)}]===${u(0)}&&m[${u(17)}]!==${u(11)}&&(m[${u(54)}]!==m[${u(28)}]||m[${u(55)}]!==m[${u(50)}]||m[${u(56)}]!==m[${u(4)}]||m[${u(78)}]!==m[${u(73)}]||m[${u(79)}]!==m[${u(74)}])){let captured=${o}_publish(m,a,p,f,authority,snapshot,encoded${ex});if(captured===${u(0)}){m[${u(54)}]=m[${u(28)}];m[${u(55)}]=m[${u(50)}];m[${u(56)}]=m[${u(4)}];m[${u(78)}]=m[${u(73)}];m[${u(79)}]=m[${u(74)}];}}sessionCounters[${q(0)}]=sessionCounters[${q(0)}]+${q(1)};let repeat=!cancelled&&m[${u(17)}]===${u(0)}&&sessionCounters[${q(0)}]<${q(maxRounds)};if(repeat){gpu.execution.tailSelf();}else{${latch}if(m[${u(82)}]===${u(0)}){m[${u(82)}]=${u(14)};}m[${u(84)}]=${u(1)};if(m[${u(20)}]!==${u(0)}){${cancel};${pr}_consume(${progressArgs});}if(m[${u(44)}]!==${u(0)}){${pr}_dispose(m,s,a,p,f,su,sf,vu,vf,sessionCounters,${u(0)}${ex});}let requestState=gpu.atomic.loadAcquireDevice(mcgsEvalRequestControl32,${q(runtime.state.requestControl32.slotState)});let batchState=gpu.atomic.loadAcquireDevice(mcgsEvalBatchControl32,${q(runtime.state.batchControl32.batchState)});if(m[${u(83)}]===${u(0)}&&m[${u(17)}]!==${u(0)}&&m[${u(17)}]!==m[${u(82)}]){m[${u(83)}]=m[${u(17)}];}if(m[${u(83)}]===${u(0)}&&(m[${u(19)}]!==${u(0)}||m[${u(44)}]!==${u(0)}||m[${u(45)}]!==${u(0)}||m[${u(80)}]!==${u(0)}||m[${u(81)}]!==${u(0)}||m[${u(32)}]!==m[${u(33)}]||m[${u(46)}]!==m[${u(47)}]||requestState!==${u(0)}||batchState!==${u(0)})){m[${u(83)}]=${u(11)};}m[${u(84)}]=${u(0)};${o}_terminal(authority,snapshot,out);${o}_terminalFacts(m,out,requestState,batchState,m[${u(82)}]);}`,1,true);
  const command=add('session','command',[p('command',U),p('commandStage',U),p('commandReply',U)],`${s}_external(command,commandStage,commandReply);`);
  const observer=add('output','observer',[p('authority',U),p('snapshot',U),p('observerOut',U),p('restriction',U),p('arena'),p('root'),p('generation'),p('epoch')],`${o}_observe(authority,snapshot,observerOut,restriction,arena,root,generation,epoch);`);
  return {source:Object.fromEntries(Object.entries(source).map(([role,parts])=>[role,parts.join('\n')])),functions,sourceFragments:Object.fromEntries(Object.entries(source).map(([owner,parts])=>[owner,parts.map((part,i)=>({name:functions[owner][i].name,source:part}))])),entryPoints:{bootstrap,control,body,controller,command,observer}};
}
