import {emitResidentStop} from './resident-stop.mjs';
import {fail} from './validation.mjs';

const U='ptr<u32>',F='ptr<f32>',N='u32';
const checked=(value,label,minimum=1)=>{if(!Number.isSafeInteger(value)||value<minimum||value>0xffff_fffe)fail('RESIDENT_GRAPH_BOUNDS',`${label} exceeds the selected finite u32 extent`);return value;};
export function createResidentGraphLayout(input){
  const L={...input};for(const [name,value]of Object.entries(L))checked(value,name);
  if(L.maxActions>L.edgeCapacity||L.ttProbes>L.ttCapacity)fail('RESIDENT_GRAPH_BOUNDS','action/probe bounds exceed selected storage');
  L.nodeMeta=128;L.edgeMeta=L.nodeMeta+L.nodeCapacity*16;L.ttMeta=L.edgeMeta+L.edgeCapacity*8;L.spanMeta=L.ttMeta+L.ttCapacity*4;L.spanBins=L.spanMeta+L.edgeCapacity*4;L.pathMeta=L.spanBins+L.maxActions+2;L.metaWords=L.pathMeta+L.pathDepth*7;
  L.edgePolicyU32=L.nodeCapacity*L.nodeU32Words;L.policyU32Words=L.edgePolicyU32+L.edgeCapacity*L.edgeU32Words;
  L.edgePolicyF32=L.nodeCapacity*L.nodeF32Words;L.policyF32Words=L.edgePolicyF32+L.edgeCapacity*L.edgeF32Words;
  L.stagedState=L.maxActions*L.actionWords;L.outcome=L.stagedState+L.stateWords;L.scratchU32Words=L.outcome+L.outcomeWords;
  L.viewActions=L.nodeU32Words;L.viewEdges=L.viewActions+L.maxActions*L.actionWords;L.viewChildren=L.viewEdges+L.maxActions*L.edgeU32Words;L.viewReady=L.viewChildren+L.maxActions*L.nodeU32Words;L.viewIds=L.viewReady+L.maxActions;L.viewU32Words=L.viewIds+L.maxActions;
  L.viewEdgeF32=L.nodeF32Words;L.viewChildF32=L.viewEdgeF32+L.maxActions*L.edgeF32Words;L.viewF32Words=L.viewChildF32+L.maxActions*L.nodeF32Words;
  for(const [name,value]of Object.entries(L))checked(value,name);checked(L.nodeCapacity*L.stateWords,'state indexing');checked(L.edgeCapacity*L.actionWords,'action indexing');
  return Object.freeze(L);
}

// Private canonical source projection. It is not a second planner or runtime.
export function generateResidentGraph(name,L,H,external){
  const u=n=>`gpu.u32(${n})`,n=role=>`${name}_${role}`,node=x=>`${u(L.nodeMeta)}+${x}*${u(16)}`,edge=x=>`${u(L.edgeMeta)}+${x}*${u(8)}`,span=x=>`${u(L.spanMeta)}+${x}*${u(4)}`;
  const ex=external.length?', '+external.map(p=>p.name).join(', '):'',basic=['m','s','a','p','f','su','sf'],signature=basic.join(', ')+ex,args=signature;
  const transitionDisposition=H.classifyTransitionResult?H.classifyTransitionResult('status'):'status';
  const common=basic.map(x=>({name:x,type:['f','sf'].includes(x)?F:U})),extra=external.map(({name,type})=>({name,type}));
  const functions=[],source=[];
  function add(role,parameters,body,returns='u32'){const fn=n(role);functions.push({name:fn,kind:'device',parameters,returns});source.push(`function ${fn}(${parameters.map(p=>p.name).join(', ')}){\n${body}\n}\n`);}
  const p=(name,type=N)=>({name,type}),all=(...tail)=>[...common,...tail,...extra];
  add('valid',[p('m',U),p('node'),p('generation')],`if(node>=m[${u(7)}]||node>=${u(L.nodeCapacity)}||generation===${u(0)}){return false;}let nb=${node('node')};return gpu.atomic.loadAcquireDevice(m,nb)===${u(1)}&&m[nb+${u(1)}]===generation;`,'bool');
  add('spanUnlink',[p('m',U),p('base')],`let sb=${span('base')};let length=m[sb];let bin=length;if(bin>${u(L.maxActions)}){bin=${u(L.maxActions+1)};}let next=m[sb+${u(1)}];let prev=m[sb+${u(2)}];if(prev===${u(4294967295)}){m[${u(L.spanBins)}+bin]=next;}else{m[${span('prev')}+${u(1)}]=next;}if(next!==${u(4294967295)}){m[${span('next')}+${u(2)}]=prev;}`,'void');
  add('spanAdd',[p('m',U),p('base'),p('length')],`let bin=length;if(bin>${u(L.maxActions)}){bin=${u(L.maxActions+1)};}let sb=${span('base')};let head=m[${u(L.spanBins)}+bin];m[sb]=length;m[sb+${u(1)}]=head;m[sb+${u(2)}]=${u(4294967295)};m[sb+${u(3)}]=${u(1)};let end=base+length-${u(1)};m[${span('end')}]=length;m[${span('end')}+${u(3)}]=${u(1)};if(head!==${u(4294967295)}){m[${span('head')}+${u(2)}]=base;}m[${u(L.spanBins)}+bin]=base;`,'void');
  add('spanFind',[p('m',U),p('length')],`if(length===${u(0)}||length>${u(L.edgeCapacity)}){return ${u(4294967295)};}let begin=length;if(begin>${u(L.maxActions)}){begin=${u(L.maxActions+1)};}for(let bin=begin;bin<=${u(L.maxActions+1)};bin++){let base=m[${u(L.spanBins)}+bin];if(base!==${u(4294967295)}&&m[${span('base')}]>=length){return base;}}return ${u(4294967295)};`);
  add('spanAllocate',[p('m',U),p('length')],`let base=${n('spanFind')}(m,length);if(base===${u(4294967295)}){return base;}let total=m[${span('base')}];${n('spanUnlink')}(m,base);let sb=${span('base')};m[sb]=length;m[sb+${u(3)}]=${u(2)};let end=base+length-${u(1)};m[${span('end')}]=length;m[${span('end')}+${u(3)}]=${u(2)};if(total>length){${n('spanAdd')}(m,base+length,total-length);}return base;`);
  add('spanFree',[p('m',U),p('base'),p('length')],`if(base>${u(L.edgeCapacity)}||length===${u(0)}||length>${u(L.edgeCapacity)}-base){return;}if(base>${u(0)}){let leftEnd=base-${u(1)};let leftTag=${span('leftEnd')};if(m[leftTag+${u(3)}]===${u(1)}){let leftLength=m[leftTag];let left=base-leftLength;${n('spanUnlink')}(m,left);base=left;length=length+leftLength;m[${u(12)}]=m[${u(12)}]+${u(1)};}}let right=base+length;if(right<${u(L.edgeCapacity)}&&m[${span('right')}+${u(3)}]===${u(1)}){let rightLength=m[${span('right')}];${n('spanUnlink')}(m,right);length=length+rightLength;m[${u(12)}]=m[${u(12)}]+${u(1)};}${n('spanAdd')}(m,base,length);`,'void');
  add('initialize',[p('m',U),p('arena')],`if(m[${u(0)}]!==${u(0)}||arena===${u(0)}){return ${u(1)};}m[${u(1)}]=arena;m[${u(2)}]=${u(4294967295)};m[${u(3)}]=${u(0)};m[${u(4)}]=${u(1)};m[${u(8)}]=${u(4294967295)};for(let bin=${u(0)};bin<=${u(L.maxActions+1)};bin++){m[${u(L.spanBins)}+bin]=${u(4294967295)};}${n('spanAdd')}(m,${u(0)},${u(L.edgeCapacity)});m[${u(0)}]=${u(1)};return ${u(0)};`);
  add('lookup',[p('m',U),p('s',U),p('candidate',U),p('candidateBase'),p('key'),...extra],`let start=key%${u(L.ttCapacity)};for(let j=${u(0)};j<${u(L.ttProbes)};j++){let index=(start+j)%${u(L.ttCapacity)};let tb=${u(L.ttMeta)}+index*${u(4)};let status=m[tb];if(status===${u(0)}){return ${u(4294967295)};}if(status===${u(1)}){let slot=m[tb+${u(2)}];let generation=m[tb+${u(3)}];if(!${n('valid')}(m,slot,generation)){m[tb]=${u(2)};}else if(m[tb+${u(1)}]===key&&${H.equalState('s',`slot*${u(L.stateWords)}`,'candidate','candidateBase')}){return slot;}}}return ${u(4294967295)};`);
  add('ttVacancy',[p('m',U),p('key')],`let start=key%${u(L.ttCapacity)};for(let j=${u(0)};j<${u(L.ttProbes)};j++){let index=(start+j)%${u(L.ttCapacity)};let tb=${u(L.ttMeta)}+index*${u(4)};if(m[tb]===${u(1)}&&!${n('valid')}(m,m[tb+${u(2)}],m[tb+${u(3)}])){m[tb]=${u(2)};}if(m[tb]!==${u(1)}){return index;}}return ${u(4294967295)};`);
  add('reclaimOne',all(),`if(m[${u(7)}]===${u(0)}){return ${u(1)};}let slot=m[${u(9)}];if(slot>=m[${u(7)}]){slot=${u(0)};}m[${u(9)}]=(slot+${u(1)})%m[${u(7)}];let nb=${node('slot')};if(m[nb]!==${u(1)}||slot===m[${u(2)}]||m[nb+${u(6)}]!==${u(0)}||m[nb+${u(7)}]!==${u(0)}||m[nb+${u(8)}]!==${u(0)}){m[${u(13)}]=m[${u(13)}]+${u(1)};return ${u(1)};}if(m[nb+${u(9)}]!==${u(0)}){m[nb+${u(9)}]=${u(0)};m[${u(13)}]=m[${u(13)}]+${u(1)};return ${u(1)};}let base=m[nb+${u(3)}];let count=m[nb+${u(4)}];let policyBase=${u(0)};let numericBase=${u(0)};if(count!==${u(0)}){policyBase=${u(L.edgePolicyU32)}+base*${u(L.edgeU32Words)};numericBase=${u(L.edgePolicyF32)}+base*${u(L.edgeF32Words)};}if(${H.retirePolicy('p',`slot*${u(L.nodeU32Words)}`,'f',`slot*${u(L.nodeF32Words)}`,'p','policyBase','f','numericBase','count')}!==${u(0)}){m[${u(13)}]=m[${u(13)}]+${u(1)};return ${u(1)};}for(let j=${u(0)};j<count;j++){let e=base+j;gpu.atomic.storeReleaseDevice(m,${edge('e')},${u(0)});}if(count!==${u(0)}){${n('spanFree')}(m,base,count);}gpu.atomic.storeReleaseDevice(m,nb,${u(0)});m[nb+${u(10)}]=m[${u(8)}];m[${u(8)}]=slot;m[${u(5)}]=m[${u(5)}]-${u(1)};m[${u(6)}]=m[${u(6)}]-count;m[${u(11)}]=m[${u(11)}]+${u(1)};return ${u(0)};`);
  add('admit',all(p('candidate',U),p('candidateBase')),`m[${u(10)}]=${u(0)};m[${u(35)}]=${u(0)};if(!${H.validateRoot('candidate','candidateBase')}){m[${u(10)}]=${u(7)};return ${u(4294967295)};}let key=${H.key('candidate','candidateBase')};let existing=${n('lookup')}(m,s,candidate,candidateBase,key${ex});if(existing!==${u(4294967295)}){m[${node('existing')}+${u(9)}]=${u(1)};return existing;}let role=${H.terminal('candidate','candidateBase','su',u(L.outcome))};if(role>${u(1)}){m[${u(10)}]=${u(7)};return ${u(4294967295)};}let count=${u(0)};if(role===${u(0)}){count=${H.actions('candidate','candidateBase','su',u(0),u(L.maxActions))};if(count===${u(0)}||count>${u(L.maxActions)}){m[${u(10)}]=${u(7)};return ${u(4294967295)};}for(let j=${u(0)};j<count;j++){if(!${H.actionValid('candidate','candidateBase','su',`j*${u(L.actionWords)}`)}){m[${u(10)}]=${u(7)};return ${u(4294967295)};}for(let k=${u(0)};k<j;k++){if(${H.actionEqual('su',`j*${u(L.actionWords)}`,'su',`k*${u(L.actionWords)}`)}){m[${u(10)}]=${u(7)};return ${u(4294967295)};}}}}
    let vacancy=${n('ttVacancy')}(m,key);let space=${u(0)};if(count!==${u(0)}){space=${n('spanFind')}(m,count);}if((m[${u(8)}]===${u(4294967295)}&&m[${u(7)}]>=${u(L.nodeCapacity)})||vacancy===${u(4294967295)}||space===${u(4294967295)}){${n('reclaimOne')}(${args});vacancy=${n('ttVacancy')}(m,key);if(count!==${u(0)}){space=${n('spanFind')}(m,count);}}
    if(m[${u(8)}]===${u(4294967295)}&&m[${u(7)}]>=${u(L.nodeCapacity)}){m[${u(10)}]=${u(3)};return ${u(4294967295)};}if(space===${u(4294967295)}){m[${u(10)}]=${u(4)};return ${u(4294967295)};}if(vacancy===${u(4294967295)}){m[${u(10)}]=${u(12)};return ${u(4294967295)};}
    let slot=m[${u(8)}];let fresh=false;if(slot===${u(4294967295)}){slot=m[${u(7)}];fresh=true;}let nb=${node('slot')};if(m[nb+${u(1)}]>=${u(4294967294)}){m[${u(10)}]=${u(10)};return ${u(4294967295)};}if(count!==${u(0)}){for(let j=${u(0)};j<count;j++){let e=space+j;if(m[${edge('e')}+${u(7)}]>=${u(4294967294)}){m[${u(10)}]=${u(10)};return ${u(4294967295)};}}}
    let base=${u(4294967295)};if(count!==${u(0)}){base=${n('spanAllocate')}(m,count);}if(fresh){m[${u(7)}]=m[${u(7)}]+${u(1)};}else{m[${u(8)}]=m[nb+${u(10)}];}m[nb+${u(1)}]=m[nb+${u(1)}]+${u(1)};m[nb+${u(2)}]=key;m[nb+${u(3)}]=base;m[nb+${u(4)}]=count;m[nb+${u(5)}]=role;m[nb+${u(6)}]=${u(0)};m[nb+${u(7)}]=${u(0)};m[nb+${u(8)}]=${u(0)};m[nb+${u(9)}]=${u(1)};for(let metric=${u(11)};metric<${u(16)};metric++){m[nb+metric]=${u(0)};}for(let w=${u(0)};w<${u(L.stateWords)};w++){s[slot*${u(L.stateWords)}+w]=candidate[candidateBase+w];}${H.initializeNode('s',`slot*${u(L.stateWords)}`,'p',`slot*${u(L.nodeU32Words)}`,'f',`slot*${u(L.nodeF32Words)}`)};
    for(let j=${u(0)};j<count;j++){let e=base+j;let eb=${edge('e')};for(let w=${u(0)};w<${u(L.actionWords)};w++){a[e*${u(L.actionWords)}+w]=su[j*${u(L.actionWords)}+w];}m[eb+${u(1)}]=slot;m[eb+${u(2)}]=m[nb+${u(1)}];m[eb+${u(3)}]=${u(4294967295)};m[eb+${u(4)}]=${u(0)};m[eb+${u(5)}]=${u(0)};m[eb+${u(6)}]=${u(0)};m[eb+${u(7)}]=m[eb+${u(7)}]+${u(1)};${H.initializeCandidate('s',`slot*${u(L.stateWords)}`,'a',`e*${u(L.actionWords)}`,'p',`${u(L.edgePolicyU32)}+e*${u(L.edgeU32Words)}`,'f',`${u(L.edgePolicyF32)}+e*${u(L.edgeF32Words)}`)};gpu.atomic.storeReleaseDevice(m,eb,${u(1)});}
    let tb=${u(L.ttMeta)}+vacancy*${u(4)};m[tb+${u(1)}]=key;m[tb+${u(2)}]=slot;m[tb+${u(3)}]=m[nb+${u(1)}];gpu.atomic.storeReleaseDevice(m,nb,${u(1)});m[tb]=${u(1)};m[${u(5)}]=m[${u(5)}]+${u(1)};m[${u(6)}]=m[${u(6)}]+count;m[${u(16)}]=m[${u(16)}]+${u(1)};m[${u(35)}]=${u(1)};return slot;`);
  add('realize',all(p('e')),`if(e>=${u(L.edgeCapacity)}){m[${u(10)}]=${u(6)};return ${u(4294967295)};}let eb=${edge('e')};let parent=m[eb+${u(1)}];if(m[eb]!==${u(1)}||!${n('valid')}(m,parent,m[eb+${u(2)}])){m[${u(10)}]=${u(6)};return ${u(4294967295)};}let child=m[eb+${u(3)}];if(child!==${u(4294967295)}&&${n('valid')}(m,child,m[eb+${u(4)}])){m[${node('child')}+${u(9)}]=${u(1)};return child;}if(child!==${u(4294967295)}){m[${u(14)}]=m[${u(14)}]+${u(1)};}
    let nb=${node('parent')};m[nb+${u(8)}]=m[nb+${u(8)}]+${u(1)};let status=${H.transition('s',`parent*${u(L.stateWords)}`,'a',`e*${u(L.actionWords)}`,'su',u(L.stagedState))};let disposition=${transitionDisposition};if(disposition!==${u(0)}){m[nb+${u(8)}]=m[nb+${u(8)}]-${u(1)};m[${u(10)}]=${u(7)};if(disposition===${u(2)}){m[${u(10)}]=${u(13)};}if(disposition===${u(3)}){m[${u(10)}]=${u(11)};${emitResidentStop(11)}}return ${u(4294967295)};}child=${n('admit')}(${basic.join(', ')},su,${u(L.stagedState)}${ex});m[nb+${u(8)}]=m[nb+${u(8)}]-${u(1)};if(child===${u(4294967295)}){return child;}if(m[${u(35)}]===${u(0)}){m[${u(15)}]=m[${u(15)}]+${u(1)};}m[eb+${u(3)}]=child;m[eb+${u(4)}]=m[${node('child')}+${u(1)}];return child;`);
  return {source:source.join('\n'),functions,sourceFragments:source};
}
